name: winarena
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - azure-ai-ml
      - azure-identity
      - azureml-core
      - azureml-dataset-runtime
      - pandas
