name: Run Agents

on:
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/amittal2001/winarena-env:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Azure Image
        shell: bash
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t amittal2001/winarena-custom:latest .
          docker push amittal2001/winarena-custom:latest
        
      - name: Azure Login with Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: azurecloud
          allow-no-subscriptions: false

      - name: Activate conda environment
        shell: bash
        run: |
          source /opt/conda/etc/profile.d/conda.sh
          conda activate winarena

      - name: Run experiment
        shell: bash
        run: |
          cd scripts
          python run_azure.py --experiments_json "experiments.json"

