name: Run Agents

on:
  workflow_dispatch:

jobs:
  run-experiment:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/amittal2001/winarena-env:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login with Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: azurecloud
          allow-no-subscriptions: false

      - name: Run experiment
        shell: bash -l {0}
        run: |
          cd scripts
          python run_azure.py --experiments_json "experiments.json"
